### ISSUE TITLE
Parse annexes

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-itu#10]
`ITU-T Z.100 Annex F2 (06/2021)`
`ITU-T G.729 Annex A (11/1996)` (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=3819)
`ITU-T Z.100 Annex C2 (10/1984)` (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=6667&lang=en)
`ITU-T Z.100 Annex B (10/1984)` (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=6665&lang=en)
`ITU-T G.722.2 Annex D (01/2002)`
`ITU-T G.729 Annex C+ (02/2000)` (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=4920&lang=en)
`ITU-T G.729 Annex E (1998) Cor. 1 (02/2000)` (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=5708&lang=en)

**Comment by ronaldtse** [comment]
Also this one "ITU-T G.780/Y.1351 (2004) Amend. 1".

<img width="481" alt="Screenshot 2023-07-04 at 5 48 12 PM" src="https://github.com/metanorma/pubid-itu/assets/11865/f8276516-d224-47e6-9687-27fe41d45319">
