### ISSUE TITLE
Support subseries of Recommendations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-itu#13]
<img width="527" alt="Screenshot 2023-07-04 at 6 09 15 PM" src="https://github.com/metanorma/pubid-itu/assets/11865/205e0ae0-3724-42a4-9b10-99d1b1fb02bd">

**Comment by mico** [comment]
https://www.itu.int/rec/T-REC-Q.400-Q.490-198811-I/en
In PDF file there are reference as "ITU-T Recommendations Q.400-490" but title "ITU-T Recommendations Q.400-Q.490".

**Comment by ronaldtse** [comment]
> Upd.: Maybe for "ITU Q.400-Q.490" it's not subseries, but just range or series?

Good point, let's treat this as range of series.
