### ISSUE TITLE
Parsing ITU-R RR (2020) (Regulatory Publications)

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-itu#3]
As I understand this is the identifier's document here: https://search.itu.int/history/HistoryDigitalCollectionDocLibrary/1.44.48.en.104.pdf

So it's a compilation of documents related to Radio Regulations. (also here https://www.itu.int/en/publications/Pages/publications.aspx?lang=en&media=electronic&parent=R-REG-RR-2020)

Identifier in URL: "R-REG-RR-2020".

So this is not a standard identifier, should we still parse it?

**Comment by andrew2net** [comment]
Since users can utilize these references we need to parse them.

**Comment by mico** [comment]
@ronaldtse @andrew2net do we have other identifiers like this?

**Comment by ronaldtse** [comment]
@mico I’m not actually sure, but there probably are.

**Comment by mico** [comment]
For “Regulatory Publications” there are other documents:
https://www.itu.int/pub/R-REG

- [Radio Regulations](https://www.itu.int/pub/R-REG-RR/en)
- [RR Navigation Tool](https://www.itu.int/pub/R-REG-RRX) 
- [RR5 Table of Frequency Allocations](https://www.itu.int/pub/R-REG-RR5)
- [Rules of Procedure](https://www.itu.int/pub/R-REG-ROP/en)
- [High Frequency Broadcasting Schedule](https://www.itu.int/pub/R-REG-HFBS/en)

I can add to parser all this publication, but if they will add something else I'll need to update parser.
If we use something like “ITU-R REG-RR”, “ITU-R REG-RTX”, “ITU-R REG-RR5”, etc. I don't need to add all these publications to parser, and it can accept any symbols after “ITU-R REG-”.

@ronaldtse what do you think? Why do we decide to use “ITU-R RR” without “REG”?

**Comment by ronaldtse** [comment]
> Why do we decide to use “ITU-R RR” without “REG”?

It's not our decision so we cannot speculate... we just have to accept it and produce that as given.

We need to also be aware that ITU-D, ITU-R and ITU-T use different identifier patterns (even for the same document type).
