### ISSUE TITLE
Need contribution identifiers

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-itu#42]
One further identifier type has emerged this year, while I have been waiting on https://github.com/metanorma/pubid-itu/issues/39:

````
Pubid::Itu::Identifier.create(**{type: :contribution, 
  group: "SG7", number: 1000}) == "SG7-C1000"
````

**Comment by opoudjis** [comment]
This one is actually higher priority than the i18n of OB Annex identifiers. Fortunately it's also very easy.

**Comment by opoudjis** [comment]
... Update please

**Comment by mico** [comment]
> One further identifier type has emerged this year, while I have been waiting on #39:
> 
> ```
> Pubid::Itu::Identifier.create(**{type: :contribution, 
>   group: "SG7", number: 1000}) == "SG7-C1000"
> ```

@opoudjis Where I can find these identifiers to confirm that format is correct?
Current SG identifiers looks like:
```
ITU-R SG07.110-2
ITU-R SG06.146-201
ITU-R SG07.146-2
```

So probably output should would be something like: `ITU-R SG07.110-2-C1000`

But it's a good question if contribution can have subseries and part and if it can which position "C1000" should be, it also can be: `ITU-R SG07-C1000.110-2`

**Comment by opoudjis** [comment]
I can only tell you that these are drafts internal to the organisation, and in the draft document, there is no ITU-R prefix. You can see samples in https://github.com/metanorma/metanorma-itu/issues/514 . These identifiers may not show up in centralised lists, especially because they are drafts.

**Comment by mico** [comment]
> I can only tell you that these are drafts internal to the organisation, and in the draft document, there is no ITU-R prefix. You can see samples in [metanorma/metanorma-itu#514](https://github.com/metanorma/metanorma-itu/issues/514) . These identifiers may not show up in centralised lists, especially because they are drafts.

@opoudjis Do I need to parse these identifiers? Or only create?
In documents identifiers looks like `SG17-C0223` but in conversation in [metanorma/metanorma-itu#514](https://github.com/metanorma/metanorma-itu/issues/514) it looks like `SG17-C-0223`. Which format I should use?

**Comment by opoudjis** [comment]
Only create, I would say. Whatever the format in the sample Word documents was; that's the intended use of these. So `SG17-C0223`.
