### ISSUE TITLE
Remove "." from Operational Bulletin identifiers

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-itu#44]
https://github.com/metanorma/pubid-itu/pull/41#issuecomment-2304148866

In original task #4 short identifiers looks like:
`ITU OB 1096`

Looking at footers of OB documents it represented as something like:
`Annex to ITU OB No. 1096`

Do we ever should use long representation, like `ITU-T Operational Bulletin No. 1096`? In which case?

**Comment by opoudjis** [comment]
> Do we ever should use long representation

I think we will eventually, in generating the document header if nothing else. But frankly, this has been held up so long that I don't think we need to implement this now. Just be aware there may be a `.to_s(format: :long)` in the future...

**Comment by opoudjis** [comment]
This can be resolved, right?
