### ISSUE TITLE
Parse amendments

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-itu#6]
Example Identifier from https://github.com/relaton/relaton-itu/blob/main/spec/relaton_itu/pubid_spec.rb:
`ITU-T G.989.2 Amd 1`
`ITU-T G.989.2 Amd. 1`

**Comment by ronaldtse** [comment]
And "ITU-T G.780/Y.1351 (2004) Amend. 1"

<img width="463" alt="Screenshot 2023-07-04 at 6 56 57 PM" src="https://github.com/metanorma/pubid-itu/assets/11865/e5291b17-ec59-4842-a601-aee8b686a776">
