### ISSUE TITLE
Parse "Dual-numbered recommendations" for ITU-R

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-itu#9]
`ITU-T G.780/Y.1351`

@ronaldtse is it two combined documents or two identifiers of the same document?

**Comment by ronaldtse** [comment]
This is a document that has 2 identifiers.

<img width="531" alt="Screenshot 2023-07-04 at 5 46 33 PM" src="https://github.com/metanorma/pubid-itu/assets/11865/bc1cabe8-dad0-48f6-92da-d6bfeebdfeac">
